steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/docgent-dev', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/docgent-dev']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'docgent-dev'
      - '--image'
      - 'gcr.io/$PROJECT_ID/docgent-dev'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-secrets'
      - 'GEMINI_API_KEY=docgent-dev-gemini-api-key:latest,GITHUB_TOKEN=docgent-dev-github-token:latest,SLACK_BOT_TOKEN=docgent-dev-slack-bot-token:latest,SLACK_SIGNING_SECRET=docgent-dev-slack-signing-secret:latest'
      - '--set-env-vars'
      - 'GITHUB_OWNER=kecbigmt,GITHUB_REPO=docgent,GITHUB_BASE_BRANCH=main'

images:
  - 'gcr.io/$PROJECT_ID/docgent-dev'

options:
  logging: CLOUD_LOGGING_ONLY